# Generated by Django 5.2.8 on 2026-03-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0004_ad_ad_render_type_alter_ad_description_alter_ad_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_format',
            field=models.CharField(blank=True, choices=[('banner', 'Banner'), ('native', 'Native'), ('interstitial', 'Interstitial')], default='banner', help_text='Ad format for GOOGLE render type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_unit_id',
            field=models.CharField(blank=True, help_text='Google AdMob ad unit ID (only for GOOGLE render type)', max_length=255, null=True),
        ),
    ]
