# Generated by Django 5.2.8 on 2026-08-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_websitepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='is_force_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='minimum_version',
            field=models.CharField(default='1.1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='release_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='update_url',
            field=models.CharField(default='https://play.google.com/store/apps/details?id=co.tz.farajayangutv.app', max_length=500),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='app_version',
            field=models.CharField(default='1.1.1', max_length=50),
        ),
    ]
