# Generated by Django 5.2.8 on 2025-12-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_notification_target_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_video_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
