# Generated by Django 5.2.8 on 2026-03-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_notification_target_video_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('video_processed', 'Video Processed'), ('video_failed', 'Video Failed'), ('new_user', 'New User'), ('comment', 'Comment'), ('SYSTEM', 'SYSTEM'), ('PROMO', 'PROMO')], default='SYSTEM', max_length=50),
        ),
    ]
