# Generated by Django 5.2.8 on 2026-08-11 06:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_notification_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('pageview', 'Page View'), ('video_play', 'Video Play'), ('video_pause', 'Video Pause'), ('video_end', 'Video End'), ('watch_seconds', 'Watch Seconds'), ('scroll', 'Scroll'), ('click', 'Click'), ('heartbeat', 'Heartbeat')], db_index=True, max_length=32)),
                ('page', models.CharField(blank=True, default='', max_length=255)),
                ('video_uid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('video_title', models.CharField(blank=True, default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='analytics_w_session_f69cde_idx'), models.Index(fields=['event_type', 'created_at'], name='analytics_w_event_t_cc7416_idx'), models.Index(fields=['video_uid', 'event_type'], name='analytics_w_video_u_11993e_idx')],
            },
        ),
    ]
