# Generated by Django 5.2.8 on 2025-12-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0011_videoadslot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_checkpoint',
            field=models.JSONField(blank=True, help_text='Checkpoint data for resuming failed tasks', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_message',
            field=models.CharField(blank=True, help_text='Current progress message', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_progress',
            field=models.IntegerField(default=0, help_text='Progress percentage 0-100'),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_stage',
            field=models.CharField(choices=[('idle', 'Idle'), ('assembling', 'Assembling Chunks'), ('downloading', 'Downloading from Storage'), ('converting', 'Converting to HLS'), ('uploading', 'Uploading HLS Files')], default='idle', help_text='Current processing stage', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assembling', 'Assembling'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
