# Generated by Django 5.2.8 on 2025-12-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0012_video_processing_checkpoint_video_processing_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='videos/originals'),
        ),
    ]
