# Generated by Django 5.2.8 on 2025-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0013_increase_video_field_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='videos'),
        ),
    ]
