# Generated by Django 5.2.8 on 2025-12-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0014_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload_completed_chunks',
            field=models.IntegerField(default=0, help_text='Number of chunks uploaded'),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_progress',
            field=models.IntegerField(default=0, help_text='Upload progress percentage 0-100'),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_total_chunks',
            field=models.IntegerField(default=0, help_text='Total number of chunks for upload'),
        ),
    ]
