# Generated by Django 5.2.8 on 2026-02-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0015_video_upload_completed_chunks_video_upload_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assembling', 'Assembling'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('killed', 'Killed')], default='pending', max_length=20),
        ),
    ]
