# Generated by Django 5.2.8 on 2026-04-18 18:38

from django.conf import settings
from django.db import migrations
from django.db.models import Count, Min


def deduplicate_views(apps, schema_editor):
    """
    Remove duplicate View rows, keeping only the earliest (lowest id)
    per (video_id, user_id) pair before the unique constraint is applied.
    """
    View = apps.get_model('streaming', 'View')
    db_alias = schema_editor.connection.alias

    duplicates = (
        View.objects.using(db_alias)
        .values('video_id', 'user_id')
        .annotate(min_id=Min('id'), count=Count('id'))
        .filter(count__gt=1)
    )

    for dup in duplicates:
        View.objects.using(db_alias).filter(
            video_id=dup['video_id'],
            user_id=dup['user_id'],
        ).exclude(id=dup['min_id']).delete()


def recalculate_views_count(apps, schema_editor):
    """
    Recalculate views_count on every Video from the now-deduplicated
    View table so the counter matches the actual unique viewer count.
    """
    Video = apps.get_model('streaming', 'Video')
    View = apps.get_model('streaming', 'View')
    db_alias = schema_editor.connection.alias

    # Build a dict of {video_id: unique_view_count} in one query
    counts = (
        View.objects.using(db_alias)
        .values('video_id')
        .annotate(total=Count('id'))
    )
    count_map = {row['video_id']: row['total'] for row in counts}

    # Bulk-update all videos — set to 0 for any with no views
    videos = Video.objects.using(db_alias).all()
    to_update = []
    for video in videos:
        correct_count = count_map.get(video.id, 0)
        if video.views_count != correct_count:
            video.views_count = correct_count
            to_update.append(video)

    if to_update:
        Video.objects.using(db_alias).bulk_update(to_update, ['views_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0017_googledriveimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: remove duplicate view rows, keep earliest per user+video
        migrations.RunPython(deduplicate_views, migrations.RunPython.noop),

        # Step 2: enforce uniqueness at the database level
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('video', 'user')},
        ),

        # Step 3: recalculate views_count to match the deduplicated rows
        migrations.RunPython(recalculate_views_count, migrations.RunPython.noop),
    ]
