# Generated by Django 5.2.8 on 2026-06-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0019_video_conversion_microservice_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoadslot',
            name='content_video',
            field=models.ForeignKey(blank=True, help_text='For video-type ads: the HLS-converted Video object containing the ad content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interceptor_ad_content', to='streaming.video'),
        ),
    ]
