# Generated by Django 5.2.8 on 2026-06-23 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0020_videoadslot_content_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'video'], name='comment_user_video_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['reply_to'], name='comment_reply_to_idx'),
        ),
    ]
