# Generated by Django 5.2.8 on 2026-07-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0024_add_upload_token_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoadslot',
            name='categories',
        ),
        migrations.AddField(
            model_name='video',
            name='download_path',
            field=models.CharField(blank=True, help_text='Path to downloadable MP4 file in R2 storage (videos/downloads/)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether push notification has been sent for this video'),
        ),
        migrations.AddField(
            model_name='video',
            name='portrait_cover',
            field=models.ImageField(blank=True, help_text='Portrait cover image for mobile app (1080x1350 recommended)', max_length=500, null=True, upload_to='videos/portrait'),
        ),
    ]
