# Generated by Django 5.2.8 on 2026-08-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0025_remove_videoadslot_categories_video_download_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoadslot',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ad_slots', to='streaming.category'),
        ),
    ]
