# Generated by Django 5.2.8 on 2026-08-06 15:12

import apps.streaming.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0028_add_video_portrait_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='portrait_cover',
            field=models.ImageField(blank=True, help_text='Portrait cover image for mobile app (1080x1350 recommended)', max_length=500, null=True, upload_to=apps.streaming.models.video_image_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.streaming.models.video_image_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='tv_landscape',
            field=models.ImageField(blank=True, help_text='TV landscape/banner image (1280x720 recommended)', max_length=500, null=True, upload_to=apps.streaming.models.video_image_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='tv_poster',
            field=models.ImageField(blank=True, help_text='TV poster image (540x720 recommended)', max_length=500, null=True, upload_to=apps.streaming.models.video_image_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='tv_square',
            field=models.ImageField(blank=True, help_text='TV square image (540x540 recommended)', max_length=500, null=True, upload_to=apps.streaming.models.video_image_upload_path),
        ),
    ]
