# Generated by Django 5.2.8 on 2026-08-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0029_alter_video_portrait_cover_alter_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
