# Generated by Django 5.2.8 on 2026-08-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0030_comment_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When the video was actually published', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When to auto-publish (null = publish now or draft)', null=True),
        ),
    ]
