# Generated by Django 5.2.8 on 2026-01-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_devices_user_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
