# Generated by Django 5.2.8 on 2026-01-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_profile_setup_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='initial_credit_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
